# config/agent_config.yaml
# Agent Configuration for HostelBuddy
agents:
  coordinator:
    name: "Hostel Coordinator"
    description: "Main routing agent for hostel queries"
    model: "llama-3.1-70b-versatile"
    temperature: 0.3
    max_tokens: 1000
    
  complaint_handler:
    name: "Complaint Specialist"
    description: "Handles maintenance and facility complaints"
    model: "llama-3.1-70b-versatile"
    temperature: 0.2
    max_tokens: 1500
    
  lost_found:
    name: "Lost & Found Assistant"
    description: "Manages lost and found items"
    model: "llama-3.1-8b-instant"
    temperature: 0.3
    max_tokens: 1000
    
  mess_management:
    name: "Mess Manager"
    description: "Handles mess-related queries and feedback"
    model: "llama-3.1-8b-instant"
    temperature: 0.4
    max_tokens: 1000
    
  rules_policy:
    name: "Policy Advisor"
    description: "Provides information about hostel rules and procedures"
    model: "llama-3.1-70b-versatile"
    temperature: 0.1
    max_tokens: 1500
    
  status_updates:
    name: "Status Monitor"
    description: "Provides current status of hostel facilities"
    model: "llama-3.1-8b-instant"
    temperature: 0.2
    max_tokens: 1000

vision_config:
  model: "llama-3.2-11b-vision-preview"
  temperature: 0.2
  max_tokens: 1000
  max_image_size: 10485760  # 10MB
  supported_formats: ["jpeg", "jpg", "png", "webp"]

system_config:
  max_query_length: 1000
  min_query_length: 3
  response_timeout: 30
  retry_attempts: 3
  
forms_config:
  base_url: "https://docs.google.com/forms/d/"
  auto_close_after_days: 30
  notification_email: "hostel.admin@example.com"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "hostelbuddy.log"